### ISSUE TITLE
Audit and fix `pointers.md` page

### ISSUE THREAD

**Issue by JerryHue** [Seneca-ICTOER/IPC144#36]
This is an sub-issue of #18.

# TO-DO

- [ ] Look for any typos
- [ ] Make sure all Markdown is correctly done. The conversion was done automatically by a tool, so there may be more idiomatic ways to do some things
- [ ] Check the page in a Desktop browser. Does it look OK? Are there any issues that need to be fixed?
- [ ] Check the page in a Mobile browser. Does it look OK? Are there any issues that need to be fixed?
- [ ] Try the page in both Light and Dark mode. Are there any issues that need to be fixed?
- [ ] Try running the page through Lighthouse: https://developers.google.com/web/tools/lighthouse. Are there any issues that need to be fixed?
- [ ] Try running the page through Web Hint: https://webhint.io/. Are there any issues that need to be fixed?
- [ ] Tables that are really wide (types.md) could be converted to use SVG or flex/grid. Make wide visual tables fit in the available viewport. Another example is the table in docs/D-Modularity/pointers.md, where we should reduce the vertical padding/margins on tables. The tables are too large, and probably shouldn't be tables at all.
- [ ] Prefer Markdown tables vs. raw HTML tags
- [ ] Fix colours in tables so it uses global styles vs. inline styles
- [ ] Use alt tags for all images. See https://supercooldesign.co.uk/blog/how-to-write-good-alt-text for suggestions
- [ ] Avoid blockquote for indentation, and prefer q or blockquote only when actually quoting. Use Admonitions instead. Example: docs/D-Modulatirty/pointers.md: there are places where > Blockquote are being used and Admonitions could replace it. “Note:” Lightbulb info Admonition.
- [ ] Make sure images work in dark and light modes. For example, docs/8-Computations/logic.md Flags image is white background, needs to work in dark. Create a “negative” or SVG so we can do Dark Mode? Can we programmatically create this negative?
- [ ] Change colours for tables (don’t use Yellow). We should use the default colour theme.
- [ ] Avoid using <b> and <i> to do emphasis.
- [ ] Use backticks and all code for memory addresses and such in tables that use things like void, int, function names, memory addresses.
- [ ] Make sure all code blocks use syntax highlighting
- [ ] Centre images horizontally (esp. when they are small) so they work well at all responsive sizes
- [ ] Check sub-script and super-script that they are correctly used in all cases
- [ ] Consider including inter-site links to other pages that have related info
- [ ] All links should have descriptive text for accessibility
- [ ] Make sure that sub-headings (right-hand side) for each document are correct.
- [ ] Improve readability of code comments (i.e., // and /*...*/) in dark mode (even light mode might need some work)
- [ ] In places where ***...*** was used as a fourth heading level, use #### instead.
- [ ] Fix Frontmatter for page to include proper id, title, slug, etc.

**Comment by JerryHue** [comment]
I believe I will have to create an issue to address the change of theme for the images. There are two problems at hand:

- "invert" the pallete of the images to adapt the dark theme. If we do a naive "invert" of the colors, we end up with images with really ugly palletes. Thus, we need to give the task of adapting the pallete to a person. However, manually editing every pixel will lead to insanity, so we need to create a program that accepts a pallete transformation table or something along those lines.

- the other problem is to be able to specify different images depending on theme. I know that the logo changes the source image depending on the theme, but this seems a special case more than a general case.

**Comment by humphd** [comment]
>     * the other problem is to be able to specify different images depending on theme. I know that the logo changes the source image depending on the theme, but this seems a special case more than a general case.

I think we can use https://docusaurus.io/docs/next/markdown-features/assets#themed-images for this.

**Comment by JerryHue** [comment]
That's pretty nice. That fixes half of the issue, now we can focus on #57 to adapt the pallete of the images to the dark theme.

Also, I have a few questions related to tables:
* The first three questions are related to the following task: 
    * > Tables that are really wide (types.md) could be converted to use SVG or flex/grid. Make wide visual tables fit in the available viewport. Another example is the table in docs/D-Modularity/pointers.md, where we should reduce the vertical padding/margins on tables. The tables are too large, and probably shouldn't be tables at all.
    * When do we know that a table must be converted to SVG or flex/grid, instead of not being a table at all? What I mean is that, in the last sentence, you say that some tables in the pointers page are "too large, and probably shouldn't be tables at all". What tables are you referring to in this case? The walkthrough tables, or the table that enumerates the pointer types corresponding to the normal types?
    * The second question is related to how to convert the tables. When you say SVG, do you mean an image such as PNG or JPG? I noticed that if I take a screenshot of an element, and then place that image as the table, resizing is taken care of with no overflow, but the text in the image does get somewhat small in small viewports.
    * The third question is related to using flex/grid to fit the table within the available viewport. I believe that using flex/grid would require to use raw HTML tags so that we can apply special CSS classes on them (I don't think markdown allows to put a CSS rule on an element). Did you perhaps mean using a general CSS rule (placed on a stylesheet, of course) that applies to all tables so that they all fit within the viewport? That way, we don't have to use raw HTML tags, I believe.
* The next question is related to the following task:
    * > Prefer Markdown tables vs. raw HTML tags
    * Is this recommendation mandatory? I believe we cannot apply Markdown tables to all tables available, since some tables have a more complicated structure that the Markdown supported by Docusaurus has no way of supporting. For example, cells that span several columns or rows.
